### ISSUE TITLE
Background Colour

### ISSUE THREAD

**Issue by snout-o** [vsanthanam/VSAlert#1]
Is it possible to set the background colour of the alert?

**Comment by vsanthanam** [comment]
There is no publicly exposed way to do this from the VSAlertController.h headers, but you could easily do this by modifying the controller's `.alertView` property, which is an instance of UIView and can be fully customized in any way you see fit. I might declare .alertView in the header at some point in a future release.

**Comment by vsanthanam** [comment]
I'll be adding official support for this in a release coming out later today

**Comment by vsanthanam** [comment]
This feature is now available in release 1.2.1
