### ISSUE TITLE
Changing alert background colour?

### ISSUE THREAD

**Issue by docash59** [vsanthanam/VSAlert#10]
Is it possible to change the colour of the alert background colour instead of white?

**Comment by vsanthanam** [comment]
Just pushed a version to the master branch that includes this API along with the proper documentation.

I will work on thoroughly testing it / adding to the next official release, but that could take a day or two, given how some other rather large changes I'm making to the overall repo structure.

If you'd like to use it now (it's working and stable):

Clone the repo, and link again `VSAlert.framework`, found in `/Release`

Then, you can create an instance of VSAlertController, and change its background color using the newly added `.alertBackgroundColor` API. You can change the background color globally via `UIAppearance` APIs. (See Apple's relevant docs for more info)

More info on this preliminary API is available in the re-build documentation, also in the master branch, but not yet in a release.

**Comment by docash59** [comment]
Awesome thank you. I'm not in desperate need for it at the moment but I will incorporate in the public release.

**Comment by vsanthanam** [comment]
I decided to release this feature independently, because the larger 2.x release will take quite sometime.  You can now use the production ready 1.2.3 release, which has the ability to change the background color, along with the appropriate documentation. It's been updated on the GitHub hosted documentation as well.

**Comment by docash59** [comment]
Awesome thank you @vsanthanam, I will grab the latest!
