### ISSUE TITLE
Haptic Feedback Support?

### ISSUE THREAD

**Issue by docash59** [vsanthanam/VSAlert#17]
Will there be support for adding/enabling haptic feedback? Like for when you tap on one of the action buttons?

**Comment by vsanthanam** [comment]
Unlikely, for a number of reasons:

1) This library is designed to mimic UIAlertController and extend it, not alter it. UIAlertController explicitly does not implement such feedback, instead passing that responsibility to it's per-instance implementation.

2) Haptic feedback should be used sparingly in iOS, and not at all on certain kinds of hardware. It should really be set up in the action's block on a case by case basic. Generic / global implementations are bound to create experience issues in some cases.

I've written a detailed blog post on how / when to use haptic feedback in iOS. If you're interested, you can read it here:

https://www.vsanthanam.com/writing/2017/10/24/haptic-feedback-done-correctly

You can pretty easily add haptic feedback using those APIs as needed.
