### ISSUE TITLE
Request for NSTextaligment

### ISSUE THREAD

**Issue by martin072** [vsanthanam/VSAlert#3]
Would it be possible to include customized text-alignment per alert? 
By default it aligns to centre, but would be nice if user can control this.

**Comment by vsanthanam** [comment]
If you'd like to try this functionality now, you can clone the repo and checkout the branch 'alert-messsage-text-alignment'.  I've edited the sample app so the first alert has its text aligned to the left.

note: this is an early implementation -- it doesn't support UIAppearance nor is it documented. It'll make its way into the master branch later today.

**Comment by vsanthanam** [comment]
This feature is now available in release 1.2.1

**Comment by martin072** [comment]
Thanks for the quick response!
