### ISSUE TITLE
Minimum image height not adjustable

### ISSUE THREAD

**Issue by josecostamartins** [vsanthanam/VSAlert#45]
**Is your feature request related to a problem? Please describe.**

I need a way for the headerViewHeightConstraint to be the same size of an image. Right now it is stretching images whem its height is smaller than 180.

**Describe the solution you'd like**

Don't stretch images, set a maximum size of 180 pixels (maintaining current behavior) but don't restrain minimum size

**Describe alternatives you've considered**

Another alternative is to have a control flag, determining if the image should strech or not.

**Additional context**
![screen shot 2018-08-20 at 19 06 24](https://user-images.githubusercontent.com/1171338/44369470-e4843580-a4ac-11e8-93a0-8aa1a8be9943.png)
![screen shot 2018-08-20 at 19 10 36](https://user-images.githubusercontent.com/1171338/44369478-e9e18000-a4ac-11e8-90d6-eb08304dbdcb.png)

**Comment by vsanthanam** [comment]
I'll have a solution for this shortly in the next release, say 2-3 days from now :)

**Comment by vsanthanam** [comment]
Resolved in merged PR -- will be cleaned up & added to next release.
